import { StyleSheet } from "react-native";
import { responsiveFontSize, responsiveWidth } from "react-native-responsive-dimensions";
import { COLORS } from "../constants";
import { FONTS } from "../constants/fonts";
export const styles = StyleSheet.create({
  headerTitle: {
    fontSize: responsiveFontSize(2.5),
    fontFamily: FONTS.Yellix,
    color: COLORS.black,
  },
  container: {
    flex: 1,
    paddingHorizontal: responsiveWidth(4),
  },
  cameraContainer: {
    backgroundColor: "#E0E0E0",
    borderRadius: responsiveWidth(4),
    aspectRatio: 4 / 5,
    marginVertical: responsiveWidth(4),
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  cameraContainerWithImage: {
    aspectRatio: 4 / 3,
    marginVertical: responsiveWidth(2),
  },
  cornerTopLeft: {
    position: "absolute",
    top: responsiveWidth(4),
    left: responsiveWidth(4),
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    borderLeftWidth: 3,
    borderTopWidth: 3,
    borderColor: COLORS.white,
    zIndex: 2,
  },
  cornerTopRight: {
    position: "absolute",
    top: responsiveWidth(4),
    right: responsiveWidth(4),
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    borderRightWidth: 3,
    borderTopWidth: 3,
    borderColor: COLORS.white,
    zIndex: 2,
  },
  cornerBottomLeft: {
    position: "absolute",
    bottom: responsiveWidth(15),
    left: responsiveWidth(4),
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    borderLeftWidth: 3,
    borderBottomWidth: 3,
    borderColor: COLORS.white,
    zIndex: 2,
  },
  cornerBottomRight: {
    position: "absolute",
    bottom: responsiveWidth(15),
    right: responsiveWidth(4),
    width: responsiveWidth(8),
    height: responsiveWidth(8),
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: COLORS.white,
    zIndex: 2,
  },
  previewImage: {
    width: "100%",
    height: "100%",
    borderRadius: responsiveWidth(4),
  },
  sampleContainer: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  sampleImage: {
    width: responsiveWidth(60),
    height: responsiveWidth(40),
  },
  captureButton: {
    position: "absolute",
    bottom: responsiveWidth(4),
    alignSelf: "center",
    width: responsiveWidth(16),
    height: responsiveWidth(16),
    borderRadius: responsiveWidth(8),
    justifyContent: "center",
    alignItems: "center",
    padding: responsiveWidth(2),
    borderWidth: 3,
    borderColor: COLORS.white,
  },
  captureInner: {
    width: responsiveWidth(12),
    height: responsiveWidth(12),
    borderRadius: responsiveWidth(6),
    backgroundColor: COLORS.white,
  },
  uploadFromPhoneContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: responsiveWidth(4),
    paddingVertical: responsiveWidth(3),
    backgroundColor:COLORS.white,
    borderRadius: responsiveWidth(2),
    marginBottom: responsiveWidth(4),
    marginHorizontal: responsiveWidth(1),
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  uploadFromPhoneText: {
    fontSize: responsiveFontSize(1.8),
    fontFamily: FONTS.Yellix,
    color: "#6C757D",
    marginRight: responsiveWidth(2),
  },
  uploadFromPhoneSubtext: {
    fontSize: responsiveFontSize(1.6),
    fontFamily: FONTS.Yellix,
    color: "#9CA3AF",
    marginRight: responsiveWidth(2),
  },
  uploadIcon: {
    marginLeft: responsiveWidth(2),
  },
  retakeButton: {
    backgroundColor: "#F3F4F6",
    borderRadius: responsiveWidth(3),
    paddingVertical: responsiveWidth(4),
    paddingHorizontal: responsiveWidth(8),
    flex: 1,
    marginRight: responsiveWidth(2),
    alignItems: "center",
  },
  retakeButtonText: {
    color: "#6B7280",
    fontSize: responsiveFontSize(2),
    fontFamily: FONTS.Yellix,
  },
  placeholderCard: {
    width: responsiveWidth(60),
    height: responsiveWidth(40),
    backgroundColor: COLORS.white,
    borderRadius: responsiveWidth(2),
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#E0E0E0",
    borderStyle: "dashed",
  },
  placeholderText: {
    fontSize: responsiveFontSize(2),
    fontFamily: FONTS.Yellix,
    color: "#6B7280",
    textAlign: "center",
    marginBottom: responsiveWidth(2),
  },
  placeholderSubtext: {
    fontSize: responsiveFontSize(1.6),
    fontFamily: FONTS.Yellix,
    color: "#9CA3AF",
    textAlign: "center",
  },
  retakeButtonContainer: {
    alignItems: "center",
    marginBottom: responsiveWidth(4),
  },
  retakeButtonMain: {
    backgroundColor: COLORS.secondaryBlue,
    borderRadius: responsiveWidth(6),
    paddingVertical: responsiveWidth(2.5),
    paddingHorizontal: responsiveWidth(8),
    alignItems: "center",
  },
  retakeButtonMainText: {
    color: COLORS.white,
    fontSize: responsiveFontSize(2),
    fontFamily: FONTS.Yellix,
  },
  bottomButtonsContainer: {
    // paddingHorizontal: responsiveWidth(4),
    paddingBottom: responsiveWidth(4),
  },
});